version: '3.9'

services:

  mysql-kc:
    image: mysql:8.0.27
    ports:
      - "3366:3306"
    restart: unless-stopped
    environment:
      # The user, password and database that Keycloak
      # is going to create and use
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_password
      MYSQL_DATABASE: keycloak_db
      # Self-Explanatory
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - keycloak-and-mysql-network

  keycloak-w:
    image: jboss/keycloak:16.1.0
    ports:
      - "8181:8080"
    restart: unless-stopped
    environment:
      # User and password for the Administration Console
      KEYCLOAK_USER: admin_user
      KEYCLOAK_PASSWORD: admin_password
      KEYCLOAK_IMPORT: /tmp/realm.json
      DB_VENDOR: mysql
      DB_ADDR: mysql-kc
      DB_PORT: 3306
      # Same values as the mysql-kc service
      DB_USER: keycloak_user
      DB_PASSWORD: keycloak_password
      DB_DATABASE: keycloak_db
    volumes:
      - ./keyckloak/import/realm.json:/tmp/realm.json:ro
      - ./keyckloak/export:/tmp/export
    command:
      - "-Dkeycloak.migration.action=export"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.realmName=goal-management"
      - "-Dkeycloak.migration.usersExportStrategy=REALM_FILE"
      - "-Dkeycloak.migration.file=/tmp/export/realm.json"
    depends_on:
      - mysql-kc
    networks:
      - keycloak-and-mysql-network

  #goal-management:


networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume:
